apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  labels:
    team: tbd
  name: sendt-soknad-alert
  namespace: tbd
spec:
  groups:
    - name: sendt-soknad-alert
      rules:
        - alert: Det er mottatt mistenkelig få søknader
          expr: sum(rate(message_counter_total{app="spedisjon", river=~"Sendte.*", validated="ok"}[10m])) < 0.01 and hour() >= 5 <= 15
          for: 1m
          annotations:
            beskrivelse: "Det er ikke registrert noen/veldig få sendte søknader i Spedisjon. Hør med Flex om det er noe krøll"
            detaljer: "Sjekk om du ser noe rart på <https://grafana.nav.cloud.nais.io/d/H8jR8MFGk/flex-kafka-lag?orgId=1&refresh=5m&viewPanel=28|grafana> eller <https://logs.adeo.no/app/r/s/NGiJM|kibana> da vel"
          labels:
            severity: "error"
            team_spleiselaget_alerts: slack
            alert_type: custom

    - name: sendt-soknad-info
      rules:
        - alert: Søknadstrømmen ser bra ut
          expr: sum(rate(message_counter_total{app="spedisjon", river=~"Sendte.*", validated="ok"}[10m])) > 0.01 and day_of_week() == 5
          for: 1h
          annotations:
            beskrivelse: "Antall mottatte søknader fra Flex ser bra ut den siste timen!"
            detaljer: "Dette er en 'alt er ok' melding, så vi ikke bekymrer oss for at noe er galt"
          labels:
            severity: "info"
            team_spleiselaget_alerts: slack
            alert_type: custom
