apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  labels:
    team: tbd
  name: inntektsmelding-alert
  namespace: tbd
spec:
  groups:
    - name: inntektmelding-alert
      rules:
        - alert: Det er mottatt mistenkelig få inntektsmeldinger
          expr: sum(rate(message_counter_total{app="spedisjon",validated="ok", river="Inntektsmeldinger"}[10m])) < 0.01 and hour() >= 5 <= 15
          for: 1m
          annotations:
            beskrivelse: "Det er ikke registert noen/veldig få inntektsmeldinger i Spedisjon. Hør med HAG om det er noe krøll."
            detaljer: "Sjekk om du ser noe rart på <https://grafana.nav.cloud.nais.io/d/oOJjNpkMz/poh-arbeidsgiver-kafka-prod?orgId=1|grafana> eller <https://logs.adeo.no/app/r/s/NGiJM|kibana> da vel"
          labels:
            severity: "error"
            team_spleiselaget_alerts: slack
            alert_type: custom

    - name: inntektsmelding-ok-info
      rules:
        - alert: Inntektsmelding strømmen ser bra ut
          expr: sum(rate(message_counter_total{app="spedisjon",validated="ok", river="Inntektsmeldinger"}[10m])) > 0.01 and day_of_week() == 5 and hour() = 9 and minute() < 30
          for: 1h
          annotations:
            beskrivelse: "Antall mottatte inntektsmeldinger fra HAG ser bra ut den siste timen!"
            detaljer: "Dette er en 'alt er ok' melding så vi ikke trenger å bekymre oss for at noe er galt"
          labels:
            severity: "info"
            team_spleiselaget_alerts: slack
            alert_type: custom
