apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spedisjon-migrering-db-policies
  namespace: tbd
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 100.71.0.167/32 # spedisjon-async
    - to:
        - ipBlock:
            cidr: 34.88.43.173/32 # spedisjon
  podSelector:
    matchLabels:
      app: spedisjon-migrate
  policyTypes:
    - Egress