apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spedisjon-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    db: spedisjon
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
#  envFrom:
#    - secret: trenger vi dette?
  secureLogs:
    enabled: true
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spedisjon-opprydding-dev-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: DATABASE_REGION
    value: "europe-north1"
  - name: DATABASE_INSTANCE
    value: "spedisjon"


