name: Spedisjon opprydding dev

on:
  push:
    paths:
      - 'Dockerfile-opprydding-dev'
      - 'spedisjon-opprydding-dev/**'
      - '.github/workflows/spedisjon-opprydding-dev.yml'
      - 'deploy/spedisjon-opprydding-dev.yml'
      - 'build.gradle.kts'
    branches:
      - opprydding-dev

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'gradle'
      - name: test and build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :spedisjon-opprydding-dev:test :spedisjon-opprydding-dev:build
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: 'tbd'
          dockerfile: Dockerfile-opprydding-dev
          image_suffix: opprydding-dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/spedisjon-opprydding-dev.yml
          IMAGE: ${{ needs.build.outputs.image }}
