name: spedisjon migrering

on:
  push:
    branches:
    - master
    paths:
    - 'spedisjon-migrering/**'
    - 'build.gradle.kts'
    - '.github/workflows/spedisjon-migrering.yml'
    - 'deploy/spedisjon-migrering.yml'
    - 'deploy/spedisjon-migrering-dev-gcp.json'
    - 'deploy/spedisjon-migrering-prod-gcp.json'
    - 'deploy/spedisjon-migrering-dev-policy.yml'
    - 'deploy/spedisjon-migrering-prod-policy.yml'

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: test and build
        run: ./gradlew :spedisjon-migrering:test :spedisjon-migrering:build
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: spedisjon-migrering
          dockerfile: Dockerfile
          docker_context: spedisjon-migrering
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
      name: deploy to dev
      needs: build
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
          - uses: actions/checkout@v4
          - uses: nais/deploy/actions/deploy@v2
            env:
                CLUSTER: dev-gcp
                RESOURCE: deploy/spedisjon-migrering-dev-policy.yml
                IMAGE: ${{ needs.build.outputs.image }}

  deployProd:
      name: deploy to prod
      needs: build
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
          - uses: actions/checkout@v4
          - uses: nais/deploy/actions/deploy@v2
            env:
                CLUSTER: prod-gcp
                RESOURCE: deploy/spedisjon-migrering-prod-policy.yml
                IMAGE: ${{ needs.build.outputs.image }}
